<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="HAH1W10BLR" name="sample.tests.ExtentReportsClassVersion3" tests="3" failures="1" timestamp="25 Jul 2018 06:11:44 GMT" time="0.020" errors="0">
  <testcase name="skipTest" time="0.010" classname="sample.tests.ExtentReportsClassVersion3">
    <skipped/>
  </testcase> <!-- skipTest -->
  <testcase name="passTest" time="0.000" classname="sample.tests.ExtentReportsClassVersion3"/>
  <testcase name="failTest" time="0.010" classname="sample.tests.ExtentReportsClassVersion3">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at sample.tests.ExtentReportsClassVersion3.failTest(ExtentReportsClassVersion3.java:18)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- failTest -->
</testsuite> <!-- sample.tests.ExtentReportsClassVersion3 -->
